[package]
name = "nekkar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
surrealdb = "1.0.0-beta.9"
tokio = "1.28.1"
